apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: ccore-backend
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          karpenter.sh/nodepool: on-demand-arm

  - target:
      kind: Deployment
      name: ccore-frontend
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          karpenter.sh/nodepool: on-demand-arm
